"""Initial revision

Revision ID: d597bec06d15
Revises:
Create Date: 2025-09-27 19:54:34.986001

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "d597bec06d15"
down_revision = None
branch_labels: tuple[str] | None = None
depends_on: tuple[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "plugin_testapi_reviews",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=True),
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("created", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("plugin_testapi_reviews_user_id_users_fkey"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("plugin_testapi_reviews_pkey")),
    )
    op.create_index(op.f("plugin_testapi_reviews_id_idx"), "plugin_testapi_reviews", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("plugin_testapi_reviews_id_idx"), table_name="plugin_testapi_reviews")
    op.drop_table("plugin_testapi_reviews")
    # ### end Alembic commands ###
